[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Persistent volume for session storage
[[deploy.volumes]]
name = "session-data"
mountPath = "/app/data"
size = "1GB"

[env]
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "production"
NPM_CONFIG_CACHE = "/tmp/.npm"
LIVE_POSTS = "false"