[build]
command = "echo '🤖 Building Autonomous Twitter Bot...' && npm install && npm run build && echo '✅ Bot build complete'"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Persistent volume for session storage
[[deploy.volumes]]
name = "session-data"
mountPath = "/app/data"
size = "1GB"

[env]
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "production"