[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInitialDelay = 30
restartPolicyType = "always"
replicas = 1

[env]
NODE_ENV = "production"
PLAYWRIGHT_BROWSERS_PATH = "0"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"