[build]
builder = "nixpacks"
buildCommand = "npm ci && npx playwright install --with-deps chromium && npm run build"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PLAYWRIGHT_BROWSERS_PATH = "0"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "false" 
NODE_ENV = "production"
PORT = "8080"