[build]
command = "echo '🔨 BUILD START' && npm run build-clean && echo '🔨 BUILD COMPLETE - checking files...' && ls -la dist/ && echo '🔨 Checking simpleMain.js...' && ls -la dist/simpleMain.js"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Persistent volume for session storage
[[deploy.volumes]]
name = "session-data"
mountPath = "/app/data"
size = "1GB"

[env]
NODE_ENV = "production"
PLAYWRIGHT_BROWSERS_PATH = "/opt/render/.cache/ms-playwright"