[build]
builder = "nixpacks"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"
replicas = 1

[env]
NODE_ENV = "production"
PLAYWRIGHT_BROWSERS_PATH = "0"