-- Learning system tables for thread posting and bandit optimization
-- posts
create table if not exists posts (
  id uuid primary key default gen_random_uuid(),
  tweet_id text unique,
  permalink text,
  posted_at timestamptz default now(),
  topic_cluster text,
  hook_type text,
  cta_type text,
  thread_len int,
  sources_json jsonb,
  model_version text
);

-- time-series metrics per post
create table if not exists post_metrics (
  id bigint generated by default as identity primary key,
  post_id uuid references posts(id) on delete cascade,
  snapshot_at timestamptz not null,
  impressions int default 0,
  likes int default 0,
  replies int default 0,
  bookmarks int default 0,
  retweets int default 0,
  profile_visits int default 0,
  follows int default 0
);
create index if not exists post_metrics_post_time_idx on post_metrics(post_id, snapshot_at);

-- candidate generations
create table if not exists content_candidates (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  topic text,
  tweets_json jsonb,
  evaluator_scores_json jsonb,
  chosen boolean default false
);

-- cached content features
create table if not exists features (
  post_id uuid primary key references posts(id) on delete cascade,
  fk_readability numeric,
  emojis_count int,
  numbers_count int,
  claim_count int,
  sources_count int
);

-- topic momentum (for trend scoring)
create table if not exists topic_clusters (
  id uuid primary key default gen_random_uuid(),
  label text unique,
  keywords text[],
  momentum_score numeric default 0
);

-- bandit posteriors per arm (simple Beta params per discrete arm combo)
create table if not exists bandit_posteriors (
  id uuid primary key default gen_random_uuid(),
  arm jsonb,          -- {hook_type, cta_type, thread_len, post_time_bucket, topic_cluster}
  alpha numeric,      -- successes
  beta numeric,       -- failures
  updated_at timestamptz default now()
);
create unique index if not exists bandit_posteriors_arm_uq on bandit_posteriors((arm::text));