#!/usr/bin/env tsx
/**
 * Collect authentication evidence for debugging auth persistence issues
 * 
 * Captures:
 * - Cookie store file presence, mtime, size
 * - AUTH_OK.json marker presence, mtime
 * - Current URL on failure
 * - Profile directory paths
 */

import * as fs from 'fs';
import * as path from 'path';

interface AuthEvidence {
  timestamp: string;
  cwd: string;
  runnerProfileDir: string;
  runnerProfileDirAbs: string;
  userDataDirAbs: string | null;
  headless: boolean;
  executionMode: string;
  cookieStoreFiles: Array<{
    path: string;
    exists: boolean;
    mtime: string | null;
    size: number | null;
  }>;
  authOkMarker: {
    path: string;
    exists: boolean;
    mtime: string | null;
    content: any | null;
  };
  currentUrl: string | null;
}

function collectAuthEvidence(): AuthEvidence {
  const cwd = process.cwd();
  const runnerProfileDir = process.env.RUNNER_PROFILE_DIR || './.runner-profile';
  const runnerProfileDirAbs = path.resolve(cwd, runnerProfileDir);
  const userDataDir = process.env.RUNNER_PROFILE_DIR 
    ? path.join(runnerProfileDirAbs, 'executor-chrome-profile')
    : path.join(runnerProfileDirAbs, 'executor-chrome-profile');
  const userDataDirAbs = path.resolve(userDataDir);
  
  const evidence: AuthEvidence = {
    timestamp: new Date().toISOString(),
    cwd,
    runnerProfileDir,
    runnerProfileDirAbs,
    userDataDirAbs: fs.existsSync(userDataDirAbs) ? userDataDirAbs : null,
    headless: process.env.HEADLESS === 'true',
    executionMode: process.env.EXECUTION_MODE || 'unknown',
    cookieStoreFiles: [],
    authOkMarker: {
      path: path.join(runnerProfileDirAbs, 'AUTH_OK.json'),
      exists: false,
      mtime: null,
      content: null,
    },
    currentUrl: null,
  };

  // Collect cookie store files (Chrome stores cookies in various locations)
  const cookiePaths = [
    path.join(userDataDirAbs, 'Default', 'Cookies'),
    path.join(userDataDirAbs, 'Cookies'),
    path.join(userDataDirAbs, 'Default', 'Network', 'Cookies'),
  ];

  for (const cookiePath of cookiePaths) {
    const exists = fs.existsSync(cookiePath);
    let mtime: string | null = null;
    let size: number | null = null;

    if (exists) {
      try {
        const stats = fs.statSync(cookiePath);
        mtime = stats.mtime.toISOString();
        size = stats.size;
      } catch (e) {
        // Ignore stat errors
      }
    }

    evidence.cookieStoreFiles.push({
      path: cookiePath,
      exists,
      mtime,
      size,
    });
  }

  // Check AUTH_OK.json marker
  const authOkPath = evidence.authOkMarker.path;
  if (fs.existsSync(authOkPath)) {
    evidence.authOkMarker.exists = true;
    try {
      const stats = fs.statSync(authOkPath);
      evidence.authOkMarker.mtime = stats.mtime.toISOString();
      const content = fs.readFileSync(authOkPath, 'utf-8');
      try {
        evidence.authOkMarker.content = JSON.parse(content);
      } catch {
        evidence.authOkMarker.content = content;
      }
    } catch (e) {
      // Ignore read errors
    }
  }

  return evidence;
}

async function main(): Promise<void> {
  const evidence = collectAuthEvidence();

  // Write evidence report
  const reportsDir = path.join(process.cwd(), 'docs', 'proofs', 'auth');
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const timestamp = Date.now();
  const reportPath = path.join(reportsDir, `auth-evidence-${timestamp}.md`);

  const report = `# Auth Evidence Collection

**Timestamp:** ${evidence.timestamp}
**Collection Time:** ${new Date().toISOString()}

## Environment

- **CWD:** \`${evidence.cwd}\`
- **RUNNER_PROFILE_DIR (raw):** \`${evidence.runnerProfileDir}\`
- **RUNNER_PROFILE_DIR (absolute):** \`${evidence.runnerProfileDirAbs}\`
- **UserDataDir (absolute):** \`${evidence.userDataDirAbs || 'NOT FOUND'}\`
- **HEADLESS:** ${evidence.headless}
- **EXECUTION_MODE:** ${evidence.executionMode}

## Cookie Store Files

${evidence.cookieStoreFiles.map(file => `
### \`${file.path}\`
- **Exists:** ${file.exists}
- **Modified:** ${file.mtime || 'N/A'}
- **Size:** ${file.size !== null ? `${file.size} bytes` : 'N/A'}
`).join('\n')}

## AUTH_OK Marker

- **Path:** \`${evidence.authOkMarker.path}\`
- **Exists:** ${evidence.authOkMarker.exists}
- **Modified:** ${evidence.authOkMarker.mtime || 'N/A'}
${evidence.authOkMarker.content ? `
- **Content:**
\`\`\`json
${JSON.stringify(evidence.authOkMarker.content, null, 2)}
\`\`\`
` : ''}

## Current URL

${evidence.currentUrl || 'N/A (not available)'}

---

*Generated by scripts/ops/collect-auth-evidence.ts*
`;

  fs.writeFileSync(reportPath, report, 'utf-8');
  console.log(`✅ Auth evidence written to: ${reportPath}`);

  // Also print summary
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('           📋 Auth Evidence Summary');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  console.log(`CWD: ${evidence.cwd}`);
  console.log(`RUNNER_PROFILE_DIR: ${evidence.runnerProfileDir}`);
  console.log(`RUNNER_PROFILE_DIR_ABS: ${evidence.runnerProfileDirAbs}`);
  console.log(`UserDataDir: ${evidence.userDataDirAbs || 'NOT FOUND'}`);
  console.log(`HEADLESS: ${evidence.headless}`);
  console.log(`EXECUTION_MODE: ${evidence.executionMode}`);
  console.log(`\nCookie Store Files:`);
  evidence.cookieStoreFiles.forEach(file => {
    console.log(`  ${file.exists ? '✅' : '❌'} ${file.path}`);
    if (file.exists) {
      console.log(`     mtime: ${file.mtime}, size: ${file.size} bytes`);
    }
  });
  console.log(`\nAUTH_OK Marker: ${evidence.authOkMarker.exists ? '✅' : '❌'} ${evidence.authOkMarker.path}`);
  if (evidence.authOkMarker.exists && evidence.authOkMarker.content) {
    console.log(`   Handle: ${evidence.authOkMarker.content.handle || 'N/A'}`);
    console.log(`   Timestamp: ${evidence.authOkMarker.content.timestamp || 'N/A'}`);
  }
}

if (require.main === module) {
  main().catch(console.error);
}
