-- =====================================================
-- OPENAI USAGE LOG TABLE
-- Core table for tracking all OpenAI API usage
-- =====================================================

BEGIN;

-- Create usage log table
CREATE TABLE IF NOT EXISTS public.openai_usage_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  model text NOT NULL,
  cost_tier text,
  intent text,
  prompt_tokens integer NOT NULL DEFAULT 0,
  completion_tokens integer NOT NULL DEFAULT 0,
  total_tokens integer NOT NULL DEFAULT 0,
  cost_usd numeric(12,6) NOT NULL DEFAULT 0,
  request_id text,
  finish_reason text,
  raw jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_openai_usage_log_created_at ON public.openai_usage_log (created_at);
CREATE INDEX IF NOT EXISTS idx_openai_usage_log_model ON public.openai_usage_log (model);
CREATE INDEX IF NOT EXISTS idx_openai_usage_log_intent ON public.openai_usage_log (intent);
CREATE INDEX IF NOT EXISTS idx_openai_usage_log_cost ON public.openai_usage_log (cost_usd);

-- Daily cost aggregation index
CREATE INDEX IF NOT EXISTS idx_openai_usage_daily ON public.openai_usage_log (date_trunc('day', created_at), cost_usd);

COMMIT;
