export class OpenAIClient {
  async generateCompletion(prompt: string, options?: any): Promise<string> {
    console.log('🤖 OpenAI Client (stub): generateCompletion called');
    return 'Simple health tip generated by stub';
  }

  async chat(messages: any[]): Promise<string> {
    console.log('🤖 OpenAI Client (stub): chat called');
    return 'Simple health tip generated by stub';
  }
}

export const openaiClient = new OpenAIClient(); 