-- ═══════════════════════════════════════════════════════════════════════════════
-- GROWTH CONTROLLER TABLES
-- For enforced policy control (cadence, sourcing, strategy)
-- ═══════════════════════════════════════════════════════════════════════════════

-- 1. growth_plans: Hourly plans generated by controller
CREATE TABLE IF NOT EXISTS growth_plans (
  plan_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  window_start TIMESTAMPTZ NOT NULL,
  window_end TIMESTAMPTZ NOT NULL,
  
  -- Cadence targets
  target_posts INTEGER NOT NULL DEFAULT 0,
  target_replies INTEGER NOT NULL DEFAULT 0,
  
  -- Feed weights (for candidate sourcing)
  feed_weights JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- Structure: { curated_accounts: 0.35, keyword_search: 0.30, viral_watcher: 0.20, discovered_accounts: 0.15 }
  
  -- Strategy weights (for content generation)
  strategy_weights JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- Structure: { topics: [...], formats: [...], generators: [...], reply_styles: [...] }
  
  -- Exploration rate
  exploration_rate NUMERIC DEFAULT 0.1, -- 0.0 to 0.3
  
  -- Metadata
  reason_summary TEXT,
  resistance_backoff_applied BOOLEAN DEFAULT false,
  backoff_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Ensure one plan per hour window
  UNIQUE(window_start)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_growth_plans_window_start 
  ON growth_plans(window_start DESC);

CREATE INDEX IF NOT EXISTS idx_growth_plans_window_end 
  ON growth_plans(window_end DESC);

COMMENT ON TABLE growth_plans IS 
  'Hourly growth plans generated by controller (enforced when GROWTH_CONTROLLER_ENABLED=true)';

-- 2. growth_execution: Track execution against plans
CREATE TABLE IF NOT EXISTS growth_execution (
  plan_id UUID PRIMARY KEY REFERENCES growth_plans(plan_id) ON DELETE CASCADE,
  
  -- Execution counters (idempotent increments)
  posts_done INTEGER DEFAULT 0,
  replies_done INTEGER DEFAULT 0,
  
  -- Timestamps
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Ensure one execution record per plan
  UNIQUE(plan_id)
);

-- Index for lookups
CREATE INDEX IF NOT EXISTS idx_growth_execution_plan_id 
  ON growth_execution(plan_id);

COMMENT ON TABLE growth_execution IS 
  'Tracks execution progress against growth plans (idempotent counters)';

-- 3. Helper function for idempotent counter increments
CREATE OR REPLACE FUNCTION increment_growth_execution(
  p_plan_id UUID,
  p_posts_delta INTEGER DEFAULT 0,
  p_replies_delta INTEGER DEFAULT 0
) RETURNS void AS $$
BEGIN
  INSERT INTO growth_execution (plan_id, posts_done, replies_done, last_updated)
  VALUES (p_plan_id, p_posts_delta, p_replies_delta, NOW())
  ON CONFLICT (plan_id) DO UPDATE SET
    posts_done = growth_execution.posts_done + p_posts_delta,
    replies_done = growth_execution.replies_done + p_replies_delta,
    last_updated = NOW();
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION increment_growth_execution IS 
  'Idempotent increment of execution counters for a growth plan';
